-- Liste des tables --
SELECT TABLE_NAME
FROM USER_TABLES
ORDER BY TABLE_NAME ASC;

-- Liste des attributs --
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM USER_TAB_COLUMNS
ORDER BY TABLE_NAME, COLUMN_ID ASC;

-- Liste des clés primaires --
SELECT UC.TABLE_NAME, UCC.COLUMN_NAME
FROM USER_CONSTRAINTS UC 
JOIN USER_CONS_COLUMNS UCC
ON UC.CONSTRAINT_NAME = UCC.CONSTRAINT_NAME
WHERE UC.CONSTRAINT_TYPE = 'P';

-- Liste des clés étrangères --
SELECT UC.TABLE_NAME, UCC.COLUMN_NAME
FROM USER_CONSTRAINTS UC 
JOIN USER_CONS_COLUMNS UCC
ON UC.CONSTRAINT_NAME = UCC.CONSTRAINT_NAME
WHERE UC.CONSTRAINT_TYPE = 'R';

-- Listes de contraintes de domaine --
SELECT UC.TABLE_NAME, UC.SEARCH_CONDITION, UCC.COLUMN_NAME
FROM USER_CONSTRAINTS UC 
JOIN USER_CONS_COLUMNS UCC
ON UC.CONSTRAINT_NAME = UCC.CONSTRAINT_NAME
WHERE UC.CONSTRAINT_TYPE = 'C';

